---
title: "Visualization"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
data("weather_df")
```

Now we have everything we need!

Start with a scaterplot
```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  labs(
    title = "Maximum vs. Minimum Temperature",
    x = "Maximum temperature (°C)",
    y = "Minimum temperature (°C)",
    color = "Weather station",
    caption = "Data from NOAA for three weather stations"
  ) +
scale_x_continuous(
  breaks = c(-10, 0, 15),
  labels = c("-10 C", "0", "Fifteen")
) +
  scale_y_continuous(
    trans = "sqrt", 
    position = "right"
  )
```


Lets look at color!!

```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point() +
  scale_colour_hue()
```


```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point() +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  )

```

## Themes
```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  theme(legend.position = "bottom")
```

```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  theme_minimal() + 
  theme(legend.position = "bottom")
```

```{r}
weather_df |>
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) +
  theme_classic() + 
  theme(legend.position = "bottom")
```


### Two more weird but useful plot things

```{r}
central_park_df = 
    weather_df |> 
  filter(name == "CentralPark_NY")

molokai_df = 
    weather_df |> 
  filter(name == "Molokai_HI")

ggplot(molokai_df, aes(x = date, y = tmax, color = name)) + 
  geom_point() +
  geom_line(data = central_park_df)

```

multple panels with different plots


```{r}
library(patchwork)

ggp_tmax_tmin =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() +
  theme(legend.position = "none")

ggp_prcp_density =
  weather_df |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.5) +
  theme(legend.position = "none")

ggp_seasonal =
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  theme(legend.position = "none")

(ggp_tmax_tmin + ggp_prcp_density) / ggp_seasonal
```
